# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
build-frontend:
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore-8
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Create FRONTEND Configs
          command: echo "export default {client_id:\"$STRAVA_CLIENT_ID\",client_secret:\"$STRAVA_CLIENT_SECRET\",maxRecomendedDistance:12000,apiurl:\"CONFIG_FILE_API_HOST\",host:\"$CONFIG_FILE_HOST\",mapBoxApi:\"$MAPBOX_API_KEY\",dev:false}" >> src/globalConfig.ts
      - run:
          name: Create BACKEND Configs
          command: echo "export default {client_id:\"$STRAVA_CLIENT_ID\",client_secret:\"$STRAVA_CLIENT_SECRET\",maxRecomendedDistance:12000,apiurl:\"CONFIG_FILE_API_HOST\",host:\"$CONFIG_FILE_HOST\",mapBoxApi:\"$MAPBOX_API_KEY\",dev:false}" >> functions/src/config.ts
      # run tests!
      - run: yarn build
deploy-job:
       docker:
         - image: circleci/node:chakracore-8
       working_directory: /tmp/my-project
       steps:
         - run:
             name: Deploy Master to Firebase
             command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
jobs:
  - build-frontend
  - deploy-job
  