# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore-8
    working_directory: ~/repo
    
    steps:
      - run: 
          name: Token ${FIREBASE_DEPLOY_TOKEN}
          command: eval echo ${FIREBASE_DEPLOY_TOKEN}
      - checkout
      - run:
          name: Create FRONTEND Configs
          command: echo "export default {build_num:\"$CIRCLE_BUILD_NUM\",client_id:\"$STRAVA_CLIENT_ID\",client_secret:\"$STRAVA_CLIENT_SECRET\",maxRecomendedDistance:12000,apiurl:\"$CONFIG_FILE_API_HOST\",host:\"$CONFIG_FILE_HOST\",mapBoxApi:\"$MAPBOX_API_KEY\",dev:false}" >> src/globalConfig.ts
      - run:
          name: Create BACKEND Configs
          command: echo "export default {client_id:\"$STRAVA_CLIENT_ID\",client_secret:\"$STRAVA_CLIENT_SECRET\",maxRecomendedDistance:12000,apiurl:\"$CONFIG_FILE_API_HOST\",host:\"$CONFIG_FILE_HOST\",mapBoxApi:\"$MAPBOX_API_KEY\",dev:false}" >> functions/src/config.ts
      - run: yarn install;cd functions;yarn install;
      - run: npm run build
      - run:
             name: Deploy Master to Firebase
             command: ./node_modules/.bin/firebase deploy --token=${FIREBASE_DEPLOY_TOKEN}
  