export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const AUTHENTICATE = 'AUTHENTICATE';
export type AUTHENTICATE = typeof AUTHENTICATE;

export const AUTHENTICATE_WITH_CODE = 'AUTHENTICATE_WITH_CODE';
export type AUTHENTICATE_WITH_CODE = typeof AUTHENTICATE_WITH_CODE;

export const AUTHENTICATE_TOKEN_SUCCESS = 'AUTHENTICATE_TOKEN_SUCCESS';
export type AUTHENTICATE_TOKEN_SUCCESS = typeof AUTHENTICATE_TOKEN_SUCCESS;

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export type AUTHENTICATE_SUCCESS = typeof AUTHENTICATE_SUCCESS;

export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export type AUTHENTICATE_ERROR = typeof AUTHENTICATE_ERROR;
