export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const AUTHENTICATE = 'AUTHENTICATE';
export type AUTHENTICATE = typeof AUTHENTICATE;

export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export type DEAUTHENTICATE = typeof DEAUTHENTICATE;

export const DEAUTHENTICATE_SUCCESS = 'DEAUTHENTICATE_SUCCESS';
export type DEAUTHENTICATE_SUCCESS = typeof DEAUTHENTICATE_SUCCESS;

export const AUTHENTICATE_WITH_CODE = 'AUTHENTICATE_WITH_CODE';
export type AUTHENTICATE_WITH_CODE = typeof AUTHENTICATE_WITH_CODE;

export const AUTHENTICATE_TOKEN_SUCCESS = 'AUTHENTICATE_TOKEN_SUCCESS';
export type AUTHENTICATE_TOKEN_SUCCESS = typeof AUTHENTICATE_TOKEN_SUCCESS;

export const AUTHENTICATE_REFRESHTOKEN = 'AUTHENTICATE_REFRESHTOKEN';
export type AUTHENTICATE_REFRESHTOKEN = typeof AUTHENTICATE_REFRESHTOKEN;

export const AUTHENTICATE_REFRESHTOKEN_SUCCESS = 'AUTHENTICATE_REFRESHTOKEN_SUCCESS';
export type AUTHENTICATE_REFRESHTOKEN_SUCCESS = typeof AUTHENTICATE_REFRESHTOKEN_SUCCESS;

export const AUTHENTICATE_REFRESH_SUCCESS = 'AUTHENTICATE_REFRESH_SUCCESS';
export type AUTHENTICATE_REFRESH_SUCCESS = typeof AUTHENTICATE_REFRESH_SUCCESS;

export const AUTHENTICATE_REFRESH_ERROR = 'AUTHENTICATE_REFRESH_ERROR';
export type AUTHENTICATE_REFRESH_ERROR = typeof AUTHENTICATE_REFRESH_ERROR;

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export type AUTHENTICATE_SUCCESS = typeof AUTHENTICATE_SUCCESS;

export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export type AUTHENTICATE_ERROR = typeof AUTHENTICATE_ERROR;


export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';
export type ACTIVITY_ERROR = typeof ACTIVITY_ERROR;

export const ACTIVITY_LIST = 'ACTIVITY_LIST';
export type ACTIVITY_LIST = typeof ACTIVITY_LIST;

export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export type ACTIVITY_LIST_SUCCESS = typeof ACTIVITY_LIST_SUCCESS;

export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export type ACTIVITY_UPDATE = typeof ACTIVITY_UPDATE;

export const ACTIVITY_UPDATE_SUCCESS = 'ACTIVITY_UPDATE_SUCCESS';
export type ACTIVITY_UPDATE_SUCCESS = typeof ACTIVITY_UPDATE_SUCCESS;

export const ACTIVITY_CLONE = 'ACTIVITY_CLONE';
export type ACTIVITY_CLONE = typeof ACTIVITY_CLONE;

export const ACTIVITY_QUEUE_TO_CLONE = 'ACTIVITY_QUEUE_TO_CLONE';
export type ACTIVITY_QUEUE_TO_CLONE = typeof ACTIVITY_QUEUE_TO_CLONE;

export const ACTIVITY_QUEUE_TO_CLONE_SUCCESS = 'ACTIVITY_QUEUE_TO_CLONE_SUCCESS';
export type ACTIVITY_QUEUE_TO_CLONE_SUCCESS = typeof ACTIVITY_QUEUE_TO_CLONE_SUCCESS;


export const ACTIVITY_REMOVE = 'ACTIVITY_REMOVE';
export type ACTIVITY_REMOVE = typeof ACTIVITY_REMOVE;

export const ACTIVITY_SELECTED = 'ACTIVITY_SELECTED';
export type ACTIVITY_SELECTED = typeof ACTIVITY_SELECTED;

export const ACTIVITY_DESELECTED = 'ACTIVITY_DESELECTED';
export type ACTIVITY_DESELECTED = typeof ACTIVITY_DESELECTED;

export const ACTIVITY_CLONE_SUCCESS = 'ACTIVITY_CLONE_SUCCESS';
export type ACTIVITY_CLONE_SUCCESS = typeof ACTIVITY_CLONE_SUCCESS;

// MAP

export const MAP_SET_NEW_ACTIVITY = 'MAP_SET_NEW_ACTIVITY';
export type MAP_SET_NEW_ACTIVITY = typeof MAP_SET_NEW_ACTIVITY;

export const MAP_UPDATE = 'MAP_UPDATE';
export type MAP_UPDATE = typeof MAP_UPDATE;


export const MAP_ERROR = 'MAP_ERROR';
export type MAP_ERROR = typeof MAP_ERROR;


// DOGS
export const ADD_DOG = 'ADD_DOG';
export type ADD_DOG = typeof ADD_DOG;

export const ADD_DOG_SUCCESS = 'ADD_DOG_SUCCESS';
export type ADD_DOG_SUCCESS = typeof ADD_DOG_SUCCESS;

export const REMOVE_DOG = 'REMOVE_DOG';
export type REMOVE_DOG = typeof REMOVE_DOG;

export const REMOVE_DOG_SUCCESS = 'REMOVE_DOG_SUCCESS';
export type REMOVE_DOG_SUCCESS = typeof REMOVE_DOG_SUCCESS;

export const ADD_DOG_ERROR = 'ADD_DOG_ERROR';
export type ADD_DOG_ERROR = typeof ADD_DOG_ERROR;

export const AUTHENTICATE_DOG = 'AUTHENTICATE_DOG';
export type AUTHENTICATE_DOG = typeof AUTHENTICATE_DOG;

export const AUTHENTICATE_DOG_SUCCESS = 'AUTHENTICATE_DOG_SUCCESS';
export type AUTHENTICATE_DOG_SUCCESS = typeof AUTHENTICATE_DOG_SUCCESS;


export const AUTHENTICATE_DOG_TOKEN_SUCCESS = 'AUTHENTICATE_DOG_TOKEN_SUCCESS';
export type AUTHENTICATE_DOG_TOKEN_SUCCESS = typeof AUTHENTICATE_DOG_TOKEN_SUCCESS;

export const DOG_ERROR = 'DOG_ERROR';
export type DOG_ERROR = typeof DOG_ERROR;


export const DOG_GET = 'DOG_GET';
export type DOG_GET = typeof DOG_GET;

export const DOG_GET_SUCCESS = 'DOG_GET_SUCCESS';
export type DOG_GET_SUCCESS = typeof DOG_GET_SUCCESS;



export const DOGS_GET_ALL = 'DOGS_GET_ALL';
export type DOGS_GET_ALL = typeof DOGS_GET_ALL;

export const DOGS_GET_ALL_SUCCESS = 'DOGS_GET_ALL_SUCCESS';
export type DOGS_GET_ALL_SUCCESS = typeof DOGS_GET_ALL_SUCCESS;
